# -*- coding: utf-8 -*-
"""day2-07-07-2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CsG5NoV1XPvJ7OCpCcmQGzvlpJ8qPl43

## Python Fundamentals for GitHub Upload
"""

# 1. Dictionary, List, Tuple, Set - 5 methods each

print("\n--- 1. Data Structures ---")

# --- Dictionary Methods ---
my_dict = {'a': 1, 'b': 2, 'c': 3}
print("\nDictionary:", my_dict)

# 1. .keys()
print("Keys:", my_dict.keys())
# 2. .values()
print("Values:", my_dict.values())
# 3. .items()
print("Items:", my_dict.items())
# 4. .get()
print("Value for 'b':", my_dict.get('b'))
# 5. .update()
my_dict.update({'d': 4})
print("After update:", my_dict)

# --- List Methods ---
my_list = [1, 2, 3, 4, 5]
print("\nList:", my_list)

# 1. .append()
my_list.append(6)
print("After append:", my_list)
# 2. .insert()
my_list.insert(0, 0)
print("After insert:", my_list)
# 3. .remove()
my_list.remove(3)
print("After remove:", my_list)
# 4. .pop()
popped_item = my_list.pop()
print(f"Popped item: {popped_item}, List after pop: {my_list}")
# 5. .sort()
my_list.sort(reverse=True)
print("After sort (descending):", my_list)

# --- Tuple Methods (limited, often use built-in functions) ---
# Tuples are immutable, so methods primarily involve information retrieval or conversion
my_tuple = (10, 20, 30, 20, 40)
print("\nTuple:", my_tuple)

# 1. .count()
print("Count of 20:", my_tuple.count(20))
# 2. .index()
print("Index of 30:", my_tuple.index(30))
# 3. Conversion to list (common workaround for 'modification')
list_from_tuple = list(my_tuple)
list_from_tuple.append(50)
print("Converted to list and appended:", tuple(list_from_tuple))
# 4. len() (often considered a 'method' in conceptual use)
print("Length of tuple:", len(my_tuple))
# 5. max() (often considered a 'method' in conceptual use)
print("Max value in tuple:", max(my_tuple))

# --- Set Methods ---
my_set1 = {1, 2, 3, 4}
my_set2 = {3, 4, 5, 6}
print("\nSet 1:", my_set1)
print("Set 2:", my_set2)

# 1. .add()
my_set1.add(5)
print("Set 1 after add:", my_set1)
# 2. .remove()
my_set1.remove(1)
print("Set 1 after remove:", my_set1)
# 3. .union()
print("Union:", my_set1.union(my_set2))
# 4. .intersection()
print("Intersection:", my_set1.intersection(my_set2))
# 5. .difference()
print("Difference (Set1 - Set2):", my_set1.difference(my_set2))

# 2. If, If-else, If-elif-else, Nested If-else (1 loop each)

print("\n--- 2. Conditional Statements ---")

# --- If statement ---
x = 10
if x > 5:
    print("If: x is greater than 5")

# --- If-else statement ---
y = 3
if y % 2 == 0:
    print("If-else: y is even")
else:
    print("If-else: y is odd")

# --- If-elif-else statement ---
score = 85
if score >= 90:
    print("If-elif-else: Grade A")
elif score >= 80:
    print("If-elif-else: Grade B")
elif score >= 70:
    print("If-elif-else: Grade C")
else:
    print("If-elif-else: Grade F")

# --- Nested If-else statement ---
age = 20
has_license = True
if age >= 18:
    if has_license:
        print("Nested If-else: Eligible to drive")
    else:
        print("Nested If-else: Not eligible to drive without a license")
else:
    print("Nested If-else: Not old enough to drive")

# 3. Break, Continue, Pass (1 example each)

print("\n--- 3. Loop Control Statements ---")

# --- Break example ---
print("Break example:")
for i in range(1, 6):
    if i == 3:
        break
    print(i)

# --- Continue example ---
print("Continue example:")
for i in range(1, 6):
    if i == 3:
        continue
    print(i)

# --- Pass example ---
print("Pass example:")
for i in range(1, 4):
    if i == 2:
        pass  # Do nothing when i is 2
    print(i)

# 4. Input method (1 example)

print("\n--- 4. Input Method ---")

# --- Input example ---
# user_name = input("Enter your name: ")
# print("Hello,", user_name)
print("Input example code is commented out to avoid blocking execution. Uncomment to test.")
# Example of how it would work:
# name = input("What is your name? ")
# print(f"Hello, {name}!")

# 5. Range, Len, Type functions (1 example each)

print("\n--- 5. Built-in Functions ---")

# --- Range example ---
print("Range example (0 to 4):", list(range(5)))
print("Range example (2 to 8, step 2):", list(range(2, 9, 2)))

# --- Len example ---
my_string = "Python"
print("Length of string 'Python':", len(my_string))
my_list_len = [10, 20, 30]
print("Length of list [10, 20, 30]:", len(my_list_len))

# --- Type example ---
num_int = 10
num_float = 10.5
str_val = "hello"
list_val = [1, 2]
dict_val = {'a': 1}

print("Type of 10:", type(num_int))
print("Type of 10.5:", type(num_float))
print("Type of 'hello':", type(str_val))
print("Type of [1, 2]:", type(list_val))
print("Type of {'a': 1}:", type(dict_val))

# 6. For, While loops (1 example each)

print("\n--- 6. Loops ---")

# --- For loop example ---
print("For loop example (iterating through a list):")
fruits = ["apple", "banana", "cherry"]
for fruit in fruits:
    print(fruit)

print("For loop example (iterating using range):")
for i in range(3):
    print("Iteration", i + 1)

# --- While loop example ---
print("While loop example:")
count = 0
while count < 3:
    print("Count:", count)
    count += 1
