# -*- coding: utf-8 -*-
"""day3-09-07-2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lwzrmIhc9Dzn7MqOdNievODy28r7hGoo

# Sustainability Data Analysis: Our World in Data CO2 Dataset

This notebook analyzes sustainability trends using the CO2 dataset from Our World in Data. We will explore carbon emissions, identify correlations between economic factors and pollution, and clean the data for further analysis.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
file_path = '/content/owid-co2-data.csv'
df = pd.read_csv(file_path)

# Initial display
display(df.head())
print(df.info())

"""## Initial Analysis and Observations

1. **Dataset Scope**: The dataset contains historical CO2 emissions data across various countries and regions, including specialized metrics like methane (`methane`), nitrous oxide (`nitrous_oxide`), and cumulative emissions.
2. **Feature Relations**:
    - `gdp` and `population`: Usually show a strong positive correlation with `co2` emissions.
    - `co2_per_capita`: Allows for a more equitable comparison between large and small nations.
    - `energy_per_capita`: Often relates directly to the industrialization level and carbon footprint of a region.
3. **Missing Values**: Many columns (like `consumption_co2` or specific gas types) have significant null counts, especially for older historical records where data collection was not standardized.
"""

# Data Cleaning: Handling Null Values

# 1. Dropping columns with more than 80% missing data as they may not be useful for general analysis
threshold = len(df) * 0.2
df_cleaned = df.dropna(thresh=threshold, axis=1).copy()

# 2. Filling missing numerical values
# For time-series sustainability data, interpolation is often more accurate than mean imputation
# We group by country (iso_code) to ensure we don't interpolate between different nations
numeric_cols = df_cleaned.select_dtypes(include=[np.number]).columns
df_cleaned[numeric_cols] = df_cleaned.groupby('iso_code')[numeric_cols].transform(lambda x: x.interpolate().fillna(method='bfill').fillna(0))

print(f"Missing values after cleaning: {df_cleaned.isnull().sum().sum()}")
display(df_cleaned.describe())

"""## Summary of Actions

1. **Data Import**: Loaded the `owid-co2-data.csv` dataset using pandas.
2. **Exploration**: Identified key features including GDP, population, and various gas emissions. Noted that many metrics are sparse for early historical years.
3. **Null Handling**:
    - Removed columns with excessive missing data (>80%).
    - Used grouped interpolation within countries to preserve local trends, followed by backward filling for early missing years.
4. **Analysis**: Prepared a cleaner version of the dataset ready for correlation analysis and sustainability trend forecasting.
"""
