# -*- coding: utf-8 -*-
"""day4-10-07-2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a4OP4PokUXGV8ySVP5TTNS4RxrQH3wVD
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, LabelEncoder

# Load the dataset
df = pd.read_csv('/content/global-data-on-sustainable-energy (1).csv')

"""## Initial Data Exploration

Let's begin by examining the first few rows of the dataset to get a sense of its structure, column names, and the type of data it contains.
"""

display(df.head())

"""Next, we'll check the general information about the DataFrame, including the data types of each column and the number of non-null values. This helps us identify potential issues like incorrect data types or missing values."""

df.info()

"""Finally, we'll generate descriptive statistics for the numerical columns. This will give us a summary of the central tendency, dispersion, and shape of the dataset's distribution, helping us understand the range and variability of the numerical features."""

display(df.describe())

"""## Data Cleaning: Column Renaming and Type Conversion

I've observed that the column `Density\n(P/Km2)` has a newline character in its name and is currently of `object` data type. This is problematic for analysis and might indicate hidden non-numeric values. My first step will be to rename this column to `Density (P/Km2)` for better readability and then investigate its contents to convert it to a numeric type.
"""

# Rename the column 'Density\n(P/Km2)' to 'Density (P/Km2)'
# Explicitly build a new list of column names and assign it to df.columns for robustness
new_column_names = []
target_old_name_found = False
new_col_name = 'Density (P/Km2)' # Desired new column name

for col in df.columns:
    # Check if the column contains 'Density' and '(P/Km2)' to identify it, despite potential newline characters
    if 'Density' in col and '(P/Km2)' in col:
        new_column_names.append(new_col_name)
        target_old_name_found = True
    else:
        new_column_names.append(col)

if target_old_name_found:
    df.columns = new_column_names
    print(f"Column successfully renamed to '{new_col_name}'.")
else:
    print(f"Warning: Original 'Density (P/Km2)' column not found. Current columns: {df.columns.tolist()}")

# Inspect unique values to identify non-numeric entries
display(df[new_col_name].value_counts(dropna=False))

# Display data types again to confirm the rename (type conversion will happen in next steps)
df.info()

"""After renaming, the `Density (P/Km2)` column still shows as an object type in `df.info()`. This is likely due to non-numeric characters. I will attempt to convert it to a numeric type, coercing any errors to `NaN`. Following this, I'll identify all columns with missing values and analyze their respective counts and percentages to decide on an appropriate handling strategy."""

# Convert 'Density (P/Km2)' to numeric, coercing errors to NaN
df['Density (P/Km2)'] = pd.to_numeric(df['Density (P/Km2)'], errors='coerce')

# Display data types again to confirm the conversion
df.info()

# Check for missing values across the dataset
missing_values = df.isnull().sum()
missing_percentage = 100 * missing_values / len(df)

missing_df = pd.DataFrame({'Missing Count': missing_values, 'Missing Percentage': missing_percentage})
missing_df = missing_df[missing_df['Missing Count'] > 0].sort_values(by='Missing Percentage', ascending=False)

display(missing_df)

"""## Handling Missing Values

Based on the missing value analysis, the columns 'Financial flows to developing countries (US $)' and 'Renewables (% equivalent primary energy)' have over 50% missing data. Dropping these columns is a reasonable approach to avoid introducing significant bias through imputation. For the remaining numerical columns with fewer missing values, I'll use median imputation, which is generally more robust to outliers than mean imputation.
"""

# Columns identified for dropping due to high percentage of missing values
columns_to_drop = [
    'Financial flows to developing countries (US $)',
    'Renewables (% equivalent primary energy)'
]

# Filter out columns that are not actually in the DataFrame to prevent KeyError
existing_columns_to_drop = [col for col in columns_to_drop if col in df.columns]

df_cleaned = df.copy() # Start with a copy of the current df state

if existing_columns_to_drop:
    df_cleaned = df_cleaned.drop(columns=existing_columns_to_drop)
    print(f"Dropped columns: {existing_columns_to_drop}")
else:
    print("No specified columns with high missing values were found to drop (they might have been dropped already).")

# Impute missing values in remaining numerical columns with the median
for column in df_cleaned.select_dtypes(include=np.number).columns:
    if df_cleaned[column].isnull().any():
        median_val = df_cleaned[column].median()
        df_cleaned[column].fillna(median_val, inplace=True)

# Verify that there are no more missing values
missing_values_after_cleaning = df_cleaned.isnull().sum()
missing_percentage_after_cleaning = 100 * missing_values_after_cleaning / len(df_cleaned)

missing_df_after_cleaning = pd.DataFrame({'Missing Count': missing_values_after_cleaning, 'Missing Percentage': missing_percentage_after_cleaning})
missing_df_after_cleaning = missing_df_after_cleaning[missing_df_after_cleaning['Missing Count'] > 0]

print("Missing values after handling:")
display(missing_df_after_cleaning)

df = df_cleaned.copy()

"""## Generalizations and Analysis: Exploring Key Features

Now that the data is clean, let's begin to understand its characteristics. We'll start by looking at the unique countries and years covered in this dataset, and then move on to visualizing the distributions of several important numerical features to gain initial insights into their patterns and potential outliers.
"""

# Generalizations about 'Entity' and 'Year'
print(f"Number of unique entities (countries): {df.Entity.nunique()}")
print(f"Years covered: {df.Year.min()} to {df.Year.max()}")

# Visualize distributions of key numerical features
plt.figure(figsize=(18, 12))

# List of key features to visualize
key_features = [
    'Access to electricity (% of population)',
    'Access to clean fuels for cooking',
    'Renewable-electricity-generating-capacity-per-capita',
    'Renewable energy share in the total final energy consumption (%)',
    'Electricity from renewables (TWh)',
    'Primary energy consumption per capita (kWh/person)',
    'Value_co2_emissions_kt_by_country',
    'gdp_per_capita'
]

for i, feature in enumerate(key_features):
    plt.subplot(3, 3, i + 1) # Adjust subplot grid as needed
    sns.histplot(df[feature], kde=True, bins=30)
    plt.title(f'Distribution of {feature}')
    plt.xlabel('')
    plt.ylabel('')

plt.tight_layout()
plt.show()

"""### Relationships Between Features: Correlation Analysis

To understand how different numerical features relate to each other, we'll compute and visualize their pairwise correlations using a heatmap. This can reveal strong positive or negative relationships, which are crucial for further analysis or modeling.
"""

# Calculate the correlation matrix for numerical columns
correlation_matrix = df.select_dtypes(include=np.number).corr()

# Plot the correlation heatmap
plt.figure(figsize=(20, 18))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=.5)
plt.title('Correlation Matrix of Numerical Features')
plt.show()

"""## Feature Engineering

I will now create new features that could be insightful for understanding sustainable energy trends. Specifically, I'll calculate:

1.  **Green_Energy_Consumption_Ratio**: The ratio of 'Electricity from renewables (TWh)' to the total electricity generated (sum of 'Electricity from fossil fuels (TWh)', 'Electricity from nuclear (TWh)', and 'Electricity from renewables (TWh)'). This feature will give us an idea of a country's reliance on renewable sources for electricity generation.
2.  **GDP_Per_Capita_Growth**: Derived from 'gdp_growth' to reflect the percentage change in GDP per capita, which is often a better indicator of individual economic prosperity and its potential links to energy consumption patterns.
"""

# Calculate total electricity generation
df['Total_Electricity_Generation_TWh'] = df['Electricity from fossil fuels (TWh)'] + \
                                         df['Electricity from nuclear (TWh)'] + \
                                         df['Electricity from renewables (TWh)']

# Create Green_Energy_Consumption_Ratio
df['Green_Energy_Consumption_Ratio'] = df['Electricity from renewables (TWh)'] / df['Total_Electricity_Generation_TWh']

# Handle potential NaN or inf values if Total_Electricity_Generation_TWh was zero
df['Green_Energy_Consumption_Ratio'].fillna(0, inplace=True)
df['Green_Energy_Consumption_Ratio'].replace([np.inf, -np.inf], 0, inplace=True)

# Rename gdp_growth for clarity in relation to gdp_per_capita
df['GDP_Per_Capita_Growth'] = df['gdp_growth'] # Assuming gdp_growth already reflects per capita growth or is used as a proxy

# Display the first few rows with new features
display(df[['Entity', 'Year', 'Electricity from renewables (TWh)', 'Total_Electricity_Generation_TWh', 'Green_Energy_Consumption_Ratio', 'GDP_Per_Capita_Growth']].head())

"""## Scaling Numerical Columns and Encoding Categorical Columns

To prepare the data for potential machine learning models, it's crucial to scale numerical features and encode categorical ones. This ensures that all features contribute equally and that models can process non-numeric data.

### Scaling Numerical Features
I'll use `StandardScaler` to transform numerical columns so they have a mean of 0 and a standard deviation of 1. This prevents features with larger scales from dominating the learning process.

### Encoding Categorical Features
The 'Entity' column (representing countries) is a categorical feature. I'll use `LabelEncoder` to convert it into numerical labels. This is suitable for nominal categorical variables when the model does not assume ordinality.
"""

# Separate numerical and categorical columns
numerical_cols = df.select_dtypes(include=np.number).columns.tolist()
categorical_cols = df.select_dtypes(include='object').columns.tolist()

# Remove 'Year' from numerical columns if it's not meant to be scaled as a continuous feature
# For time-series analysis, 'Year' might be handled differently, but for general ML, it can be treated numerically or as an identifier.
# For now, let's keep 'Year' as a numerical feature, as it indicates a trend.

# Initialize StandardScaler
scaler = StandardScaler()

# Apply scaling to numerical columns (excluding 'Year' for now if specific year-based analysis is intended, but for general scaling, it can be included)
df_scaled = df.copy()
df_scaled[numerical_cols] = scaler.fit_transform(df_scaled[numerical_cols])

print("Scaled Numerical Features (first 5 rows of numerical columns):")
display(df_scaled[numerical_cols].head())

# Apply Label Encoding to 'Entity' column
encoder = LabelEncoder()
df_encoded = df_scaled.copy()
df_encoded['Entity_Encoded'] = encoder.fit_transform(df_encoded['Entity'])

# Drop the original 'Entity' column if it's no longer needed
df_encoded = df_encoded.drop(columns=['Entity'])

print("Encoded Categorical Features (first 5 rows of relevant columns):")
display(df_encoded[['Entity_Encoded', 'Year']].head())

# Display info of the final processed DataFrame
print("\nInfo of the final processed DataFrame:")
df_encoded.info()

"""## Insights and Justification

Throughout this analysis, several key steps were taken, each with a specific rationale:

1.  **Initial Data Exploration**: We started by using `df.head()`, `df.info()`, and `df.describe()` to quickly grasp the dataset's structure, identify data types, check for initial missing values, and understand the basic statistics of numerical columns. This is crucial for forming an initial understanding of the data's quality and characteristics.

2.  **Column Renaming and Type Conversion**: The column `Density\n(P/Km2)` had a newline character and was of 'object' type. This was addressed by programmatically renaming it to `Density (P/Km2)` for readability and converting it to a numeric type using `pd.to_numeric(errors='coerce')`. This ensured that the column could be used in numerical calculations and visualizations, while `errors='coerce'` robustly handled any non-numeric entries by turning them into `NaN`.

3.  **Handling Missing Values**:
    *   Columns with a very high percentage of missing values (e.g., 'Financial flows to developing countries (US $)' and 'Renewables (% equivalent primary energy)') were dropped. This is because imputing such a large proportion of missing data could introduce significant bias and distort the true underlying patterns.
    *   For other numerical columns with fewer missing values, **median imputation** was used. The median is preferred over the mean in the presence of skewed distributions or outliers, as it is less sensitive to extreme values, thus providing a more robust central tendency measure for imputation.

4.  **Generalizations and Visualizations (Histograms and Correlation Heatmap)**:
    *   **Histograms** were used to visualize the distribution of key numerical features. This helped in understanding the spread, central tendency, and skewness of variables like 'Access to electricity', 'Renewable energy share', and 'gdp_per_capita'. These plots can reveal outliers or multimodal distributions.
    *   A **correlation heatmap** was generated to visualize the pairwise relationships between all numerical features. This is invaluable for identifying strong positive or negative correlations, which can suggest potential dependencies, multicollinearity, or areas for further investigation (e.g., strong positive correlation between 'Access to electricity' and 'gdp_per_capita').

5.  **Feature Engineering**:
    *   **Green_Energy_Consumption_Ratio** was created to provide a normalized measure of renewable energy's contribution to total electricity. This composite feature can be more informative than individual absolute values and directly represents a key aspect of sustainability.
    *   **GDP_Per_Capita_Growth** was directly taken from `gdp_growth` assuming it's a proxy for per capita economic changes, aiming to capture economic dynamism relevant to energy policies and consumption.

6.  **Feature Scaling (StandardScaler)**: Numerical features were scaled using `StandardScaler`. This is a critical preprocessing step for many machine learning algorithms (e.g., gradient descent-based models, SVMs, k-Nearest Neighbors) that are sensitive to the scale of input features. Scaling ensures that no single feature dominates due to its larger magnitude, allowing algorithms to converge faster and perform better.

7.  **Categorical Encoding (LabelEncoder)**: The 'Entity' column, representing countries, was transformed using `LabelEncoder`. This converts categorical text data into numerical format, making it palatable for machine learning algorithms. While `OneHotEncoder` is often preferred for nominal data to avoid implying ordinality, `LabelEncoder` is a simpler choice when the number of categories is very high or for tree-based models that are less sensitive to such implications.

These steps collectively transform the raw dataset into a clean, well-structured, and appropriately formatted DataFrame, ready for advanced analysis or machine learning model development related to sustainable energy and related factors.
"""
