# -*- coding: utf-8 -*-
"""day5 12-07-2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UHja5x0pz8f6mHW2LMHlc4IBshBp8W5_
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score, classification_report, confusion_matrix

import datetime
import os

"""## 1. Data Loading and Initial Exploration

First, I will load the two datasets into pandas DataFrames and display their initial rows and information to understand their structure, data types, and potential issues like missing values.
"""

# Load the renewable_energy dataset
renewable_energy_df = pd.read_csv('/content/renewable_energy.csv')

# Display the first 5 rows and information about the dataset
print("\n--- Renewable Energy Dataset ---")
display(renewable_energy_df.head())
print(renewable_energy_df.info())

"""### Initial Observations on Renewable Energy Dataset:
*   The dataset contains columns like `country`, `year`, `energy_consumption`, `renewable_share_of_electricity`, etc.
*   Data types seem appropriate, but `energy_consumption` and `renewable_share_of_electricity` might be numerical.
*   There might be missing values, especially in numerical columns, which will need to be addressed later.
"""

# Load the climate_change_indicators dataset
climate_change_df = pd.read_csv('/content/climate_change_indicators.csv')

# Display the first 5 rows and information about the dataset
print("\n--- Climate Change Indicators Dataset ---")
display(climate_change_df.head())
print(climate_change_df.info())

"""### Initial Observations on Climate Change Indicators Dataset:
*   This dataset seems to have `country`, `year`, and various `indicator` columns, potentially containing different climate-related metrics.
*   The `Value` column will likely hold the actual indicator data.
*   Similar to the first dataset, missing values are anticipated, particularly in the `Value` column, as not all indicators will be available for all countries and years.
*   The `Indicator Name` column is categorical and will need careful handling, possibly through pivoting or filtering to create meaningful features.

Next, I will proceed with handling null values and feature engineering based on these initial observations.

## 2. Data Cleaning and Preprocessing

### Renewable Energy Dataset Preprocessing

First, I'll standardize column names and handle missing values in the `renewable_energy_df`.
"""

# Rename columns for consistency
renewable_energy_df.rename(columns={'LOCATION': 'Country', 'TIME': 'Year'}, inplace=True)

# Drop 'Flag Codes' due to many missing values and limited analytical use
renewable_energy_df.drop('Flag Codes', axis=1, inplace=True)

# Impute missing 'Value' with the median for simplicity
median_value_renewable = renewable_energy_df['Value'].median()
renewable_energy_df['Value'].fillna(median_value_renewable, inplace=True)

print("\n--- Renewable Energy Dataset after preprocessing ---")
display(renewable_energy_df.head())
print(renewable_energy_df.info())

"""### Climate Change Indicators Dataset Preprocessing

Next, I'll preprocess the `climate_change_df`. This involves melting the year columns into a 'Year' and 'Value' format, and handling any remaining missing values.
"""

# Melt the DataFrame to convert year columns (F1961-F2022) into 'Year' and 'Value' columns
year_cols = [col for col in climate_change_df.columns if col.startswith('F') and col[1:].isdigit()]
id_vars = [col for col in climate_change_df.columns if col not in year_cols]

climate_change_long_df = climate_change_df.melt(id_vars=id_vars,
                                           value_vars=year_cols,
                                           var_name='Year',
                                           value_name='Value')

# Convert 'Year' column from 'FXXXX' format to integer year
climate_change_long_df['Year'] = climate_change_long_df['Year'].str[1:].astype(int)

# Handle missing values in the 'Value' column (impute with median)
median_value_climate = climate_change_long_df['Value'].median()
climate_change_long_df['Value'].fillna(median_value_climate, inplace=True)

# Drop rows with missing 'ISO2' if any, as it's a country identifier
climate_change_long_df.dropna(subset=['ISO2'], inplace=True)

print("\n--- Climate Change Indicators Dataset after preprocessing (long format) ---")
display(climate_change_long_df.head())
print(climate_change_long_df.info())

# Pivot the climate_change_long_df to have indicators as columns
# We'll use Country, Year, ISO3 as identifiers and Indicator as the column to pivot
# Using 'first' for aggregation in case of duplicate Country-Year-Indicator combinations, though ideally there shouldn't be.
climate_change_indicators_pivoted_df = climate_change_long_df.pivot_table(
    index=['Country', 'Year', 'ISO3'],
    columns='Indicator',
    values='Value',
    aggfunc='first'
).reset_index()

# Rename the pivoted columns for better readability (remove special characters if any)
climate_change_indicators_pivoted_df.columns.name = None # Remove the 'Indicator' name from columns

print("\n--- Climate Change Indicators Pivoted Dataset ---")
display(climate_change_indicators_pivoted_df.head())
print(climate_change_indicators_pivoted_df.info())

"""### Merging the Datasets

Now, I will merge the processed `renewable_energy_df` with the `climate_change_indicators_pivoted_df` on 'Country' and 'Year' to create a comprehensive dataset for our analysis.
"""

# Merge the two datasets on 'Country' and 'Year'
# Using an inner merge to keep only the common countries and years in both datasets
merged_df = pd.merge(renewable_energy_df,
                     climate_change_indicators_pivoted_df,
                     on=['Country', 'Year'],
                     how='inner')

print("\n--- Merged Dataset ---")
display(merged_df.head())
print(merged_df.info())

"""## 3. Generalizations, Analysis, and Understanding of the Dataset

Now that we have merged the two datasets, let's analyze the `merged_df` to understand its structure, content, and the relationships between its features.

### Generalizations and Observations:

*   **Combined Information**: The `merged_df` now contains information about renewable energy consumption and various climate change indicators for different countries and years.
*   **Key Features**: We have 'Country' and 'Year' as primary identifiers. `Value` from `renewable_energy_df` now represents a specific energy metric, and we have multiple new columns representing different climate indicators (e.g., 'Temperature change...', 'GHG emissions...').
*   **Potential Relationships**: We can now investigate potential relationships, such as:
    *   How does the `renewable_share_of_electricity` relate to `Temperature change`?
    *   Are countries with higher `energy_consumption` also having higher `GHG emissions`?
    *   What are the trends of these indicators over `Year` for different `Country`s?
*   **Data Granularity**: The data is aggregated at a country-year level, which is suitable for macro-level analysis.

### Handling Remaining Null Values

Although we've handled nulls in individual dataframes, merging might introduce new `NaN`s if a country-year combination exists in one dataset but not the other, or if certain indicators were not present for all country-year combinations even after pivoting. Let's check for any remaining null values in the `merged_df` and decide on a strategy.
"""

# Check for remaining null values in the merged dataset
print("\n--- Missing values in Merged Dataset ---")
print(merged_df.isnull().sum()[merged_df.isnull().sum() > 0])

# For simplicity, we'll fill any remaining numerical NaN values with the median of their respective columns.
# This is a common strategy when the proportion of missing values is not too high and we want to retain data.
for col in merged_df.select_dtypes(include=np.number).columns:
    if merged_df[col].isnull().any():
        median_val = merged_df[col].median()
        merged_df[col].fillna(median_val, inplace=True)

print("\n--- Missing values after final imputation ---")
print(merged_df.isnull().sum()[merged_df.isnull().sum() > 0])

"""### Feature Engineering (Column Selection)

The `INDICATOR`, `SUBJECT`, `MEASURE`, and `FREQUENCY` columns from the original `renewable_energy_df` describe the `Value` column itself (total renewable energy in KTOE, annually). Since we have specific climate change indicators from the other dataset, these columns from the renewable energy data can be dropped to simplify our feature set, as the `Value` column directly represents the quantity we're interested in.

Also, `ObjectId` is just an identifier and can be dropped.
"""

columns_to_drop = ['INDICATOR', 'SUBJECT', 'MEASURE', 'FREQUENCY', 'ObjectId', 'CTS_Code', 'CTS_Name', 'CTS_Full_Descriptor', 'Source', 'Unit']
# Drop columns that are metadata or not relevant for direct modeling
merged_df.drop(columns=columns_to_drop, inplace=True, errors='ignore')

print("\n--- Merged Dataset after Feature Engineering ---")
display(merged_df.head())
print(merged_df.info())

"""## 4. Reporting Understanding of the Dataset

With the datasets merged and initial cleaning/engineering done, let's establish a deeper understanding of the combined dataset. Our `merged_df` now contains:

*   **Geographical and Temporal Coverage**: Data for various `Country`'s across multiple `Year`s.
*   **Renewable Energy Data**: The `Value` column (from `renewable_energy_df`) represents the total renewable energy consumption (likely in KTOE) for a given country and year.
*   **Climate Change Indicators**: Several columns (e.g., 'Temperature change with respect to a baseline average', 'GHG emissions excluding LULUCF, per capita') providing specific climate-related metrics.
*   **Identifiers**: `Country`, `Year`, and `ISO3` serve as primary keys and identifiers.

### Descriptive Statistics

Let's look at the descriptive statistics for numerical columns to understand their ranges, central tendencies, and distributions.
"""

print("\n--- Descriptive Statistics of Merged Dataset ---")
display(merged_df.describe())

"""## Investigating the Empty Merged DataFrame

The `merged_df` is currently empty, which suggests that there are no common 'Country' and 'Year' combinations when performing the inner join. Let's inspect the unique countries and the range of years in both `renewable_energy_df` and `climate_change_indicators_pivoted_df` to diagnose this issue.
"""

print("\n--- Unique Countries in Renewable Energy DF ---")
print(renewable_energy_df['Country'].unique())
print("\n--- Year Range in Renewable Energy DF ---")
print(f"Min Year: {renewable_energy_df['Year'].min()}, Max Year: {renewable_energy_df['Year'].max()}")

print("\n--- Unique Countries in Climate Change Pivoted DF ---")
print(climate_change_indicators_pivoted_df['Country'].unique())
print("\n--- Year Range in Climate Change Pivoted DF ---")
print(f"Min Year: {climate_change_indicators_pivoted_df['Year'].min()}, Max Year: {climate_change_indicators_pivoted_df['Year'].max()}")

"""## Fixing the Merge Issue: Harmonizing Country Identifiers

The previous investigation revealed that the 'Country' column in `renewable_energy_df` contains ISO codes (e.g., 'AUS'), while the 'Country' column in `climate_change_indicators_pivoted_df` uses full country names. To resolve this, we will use the 'ISO3' column from `climate_change_indicators_pivoted_df` as our common country identifier, renaming it to 'Country' for consistency before merging.
"""

# Rename 'ISO3' to 'Country' in climate_change_indicators_pivoted_df to match renewable_energy_df's country identifier format
climate_change_indicators_pivoted_df.rename(columns={'ISO3': 'Country_ISO'}, inplace=True)

# Now, let's merge on the common ISO country code and Year
# We'll use 'Country_ISO' from climate_change_indicators_pivoted_df and 'Country' from renewable_energy_df
merged_df = pd.merge(renewable_energy_df,
                     climate_change_indicators_pivoted_df,
                     left_on=['Country', 'Year'],
                     right_on=['Country_ISO', 'Year'],
                     how='inner')

# Drop the redundant 'Country_ISO' column after merging
merged_df.drop(columns=['Country_ISO'], inplace=True)

print("\n--- Merged Dataset (Fixed) ---")
display(merged_df.head())
print(merged_df.info())

"""### Re-checking for Remaining Null Values and Feature Engineering

Now that the merge is corrected, let's re-run the null value check and the feature engineering steps to ensure everything is consistent.
"""

# Check for remaining null values in the merged dataset
print("\n--- Missing values in Merged Dataset (after fix) ---")
print(merged_df.isnull().sum()[merged_df.isnull().sum() > 0])

# For simplicity, we'll fill any remaining numerical NaN values with the median of their respective columns.
for col in merged_df.select_dtypes(include=np.number).columns:
    if merged_df[col].isnull().any():
        median_val = merged_df[col].median()
        merged_df[col].fillna(median_val, inplace=True)

print("\n--- Missing values after final imputation (after fix) ---")
print(merged_df.isnull().sum()[merged_df.isnull().sum() > 0])

columns_to_drop = ['INDICATOR', 'SUBJECT', 'MEASURE', 'FREQUENCY']
# Drop columns that are metadata or not relevant for direct modeling
merged_df.drop(columns=columns_to_drop, inplace=True, errors='ignore')

print("\n--- Merged Dataset after Feature Engineering (Fixed) ---")
display(merged_df.head())
print(merged_df.info())

print("\n--- Descriptive Statistics of Merged Dataset (Fixed) ---")
display(merged_df.describe())

"""### Key Generalizations and Analysis:

*   **Range of Years**: We have data spanning a significant period, allowing for trend analysis.
*   **Indicator Variety**: The climate change indicators cover various aspects, from temperature change to GHG emissions, offering a multi-faceted view of climate impact.
*   **Correlation Potential**: Intuitively, we expect an inverse relationship between `Value` (renewable energy consumption) and `GHG emissions`, and possibly `Temperature change`. Countries investing more in renewable energy might show lower emission levels or slower temperature increases.
*   **Country-Specific Patterns**: Different countries will likely exhibit diverse patterns in both renewable energy adoption and climate change impacts, which can be explored through grouping and aggregation.
*   **Data Distribution**: The `describe()` output gives us a glimpse into the distribution of numerical features. Some may be skewed, suggesting the need for transformations or robust modeling techniques.

Now, let's move on to visualizing these patterns and relationships using Seaborn.

## 5. Visualizing the Dataset with Seaborn

Before visualizing, let's clean up the country columns. We have `Country_x` (ISO codes) and `Country_y` (full names). I will rename `Country_x` to `Country` and drop `Country_y` to maintain a single country identifier.
"""

# Rename 'Country_x' to 'Country' and drop 'Country_y'
merged_df.rename(columns={'Country_x': 'Country'}, inplace=True)
merged_df.drop(columns=['Country_y'], inplace=True)

print("\n--- Merged Dataset after Country Column Cleanup ---")
display(merged_df.head())
print(merged_df.info())

"""### Visualization 1: Renewable Energy Consumption Over Time for Top Countries

Let's visualize the trend of renewable energy consumption (`Value`) over `Year` for a few selected top countries to see their development.
"""

# Get top 5 countries by mean renewable energy consumption for visualization
top_countries = merged_df.groupby('Country')['Value'].mean().nlargest(5).index

plt.figure(figsize=(12, 6))
sns.lineplot(data=merged_df[merged_df['Country'].isin(top_countries)],
             x='Year',
             y='Value',
             hue='Country',
             marker='o')
plt.title('Renewable Energy Consumption Over Time for Top 5 Countries')
plt.xlabel('Year')
plt.ylabel('Renewable Energy Consumption (KTOE)')
plt.grid(True)
plt.legend(title='Country')
plt.show()

"""### Insight from Visualization 1:

*   This plot shows the general trend of increasing renewable energy consumption over the years, particularly for countries with higher average consumption. It highlights which countries are leading in this aspect.

### Visualization 2: Temperature Change Over Time for Top Countries

Now, let's visualize the trend of `Temperature change with respect to a baseline climatology, corresponding to the period 1951-1980` over `Year` for the same top countries to see if there are any related patterns.
"""

plt.figure(figsize=(12, 6))
sns.lineplot(data=merged_df[merged_df['Country'].isin(top_countries)],
             x='Year',
             y='Temperature change with respect to a baseline climatology, corresponding to the period 1951-1980',
             hue='Country',
             marker='o')
plt.title('Temperature Change Over Time for Top 5 Countries (by Renewable Energy)')
plt.xlabel('Year')
plt.ylabel('Temperature Change (Celsius)')
plt.grid(True)
plt.legend(title='Country')
plt.show()

"""### Insight from Visualization 2:

*   This plot helps us understand how temperature changes have occurred in the same set of countries. We can observe if there's a general warming trend and if countries with high renewable energy adoption show different temperature change patterns compared to others (though this plot alone won't confirm causality).

### Visualization 3: Relationship between Renewable Energy and Temperature Change

Let's use a scatter plot to explore the direct relationship between renewable energy consumption and temperature change across all available data points.
"""

plt.figure(figsize=(10, 8))
sns.scatterplot(data=merged_df,
                x='Value',
                y='Temperature change with respect to a baseline climatology, corresponding to the period 1951-1980',
                alpha=0.6)
plt.title('Renewable Energy Consumption vs. Temperature Change')
plt.xlabel('Renewable Energy Consumption (KTOE)')
plt.ylabel('Temperature Change (Celsius)')
plt.grid(True)
plt.show()

"""### Insight from Visualization 3:

*   The scatter plot visually represents whether a correlation exists between higher renewable energy consumption and temperature changes. A clear pattern (e.g., negative correlation) would suggest that higher renewable energy usage might be associated with less temperature increase, but this requires more rigorous statistical analysis.

### Visualization 4: Distribution of Renewable Energy Consumption

Let's look at the distribution of the `Value` (renewable energy consumption) using a histogram.
"""

plt.figure(figsize=(10, 6))
sns.histplot(merged_df['Value'], bins=50, kde=True)
plt.title('Distribution of Renewable Energy Consumption')
plt.xlabel('Renewable Energy Consumption (KTOE)')
plt.ylabel('Frequency')
plt.show()

"""### Insight from Visualization 4:

*   The histogram shows that renewable energy consumption values are highly skewed to the right, with most countries having relatively low consumption and a few outliers with very high consumption. This suggests that the data might benefit from scaling or transformation before being used in models.

These visualizations provide a foundational understanding of our combined dataset. Next, we will perform scaling on numerical columns and encoding on categorical columns as specified in the task.

## 6. Feature Scaling and Categorical Encoding

To prepare our `merged_df` for machine learning algorithms, we need to perform two key preprocessing steps:

1.  **Scaling Numerical Columns**: Numerical features often have different scales and ranges, which can affect the performance of many machine learning algorithms. `StandardScaler` will transform the data to have a mean of 0 and a standard deviation of 1.
2.  **Encoding Categorical Columns**: Machine learning models typically require numerical input. Categorical features like 'Country' need to be converted into a numerical representation. `pd.get_dummies` is suitable for this, creating binary columns for each category.
"""

# Identify numerical and categorical columns
numerical_cols = merged_df.select_dtypes(include=np.number).columns.tolist()
categorical_cols = merged_df.select_dtypes(include='object').columns.tolist()

# Remove 'Year' from numerical columns if it's used as a direct feature, as it's often treated differently or for time series
# For this task, we will scale 'Year' as well, assuming it contributes linearly to the models.

print(f"Numerical columns: {numerical_cols}")
print(f"Categorical columns: {categorical_cols}")

"""### Applying StandardScaler to Numerical Columns"""

scaler = StandardScaler()
merged_df[numerical_cols] = scaler.fit_transform(merged_df[numerical_cols])

print("\n--- Merged Dataset after Numerical Scaling (first 5 rows) ---")
display(merged_df.head())

"""### Applying One-Hot Encoding (pd.get_dummies) to Categorical Columns"""

# Apply one-hot encoding to categorical columns
merged_df = pd.get_dummies(merged_df, columns=categorical_cols, drop_first=True)

print("\n--- Merged Dataset after Categorical Encoding (first 5 rows) ---")
display(merged_df.head())
print(merged_df.info())

"""### Insights on Scaling and Encoding:

*   **Why Scaling?**: Numerical features like 'Value' (renewable energy consumption) and 'Temperature change' had very different scales. Scaling ensures that no single feature dominates the learning process, which is crucial for algorithms sensitive to feature magnitudes (e.g., linear regression, SVMs, neural networks).
*   **Why Encoding?**: The 'Country' column, being a nominal categorical variable, needed to be converted into a numerical format. One-hot encoding creates a new binary column for each unique country (minus one to avoid multicollinearity), allowing the models to process this information effectively without assuming any ordinal relationship between countries.
*   **Impact on Dataset**: The dataset's width (number of columns) has significantly increased due to one-hot encoding, as each unique country now has its own column. This is a common consequence of handling high-cardinality categorical features.

Now our data is fully preprocessed and ready for splitting into training and testing sets, and then applying machine learning algorithms.

## 7. Splitting Data into Training and Testing Sets

Before applying machine learning algorithms, we need to split our preprocessed data into features (X) and target variables (y), and then further divide them into training and testing sets. We will define two different target variables:

1.  **Regression Target (`y_reg`)**: `Value` (Scaled Renewable Energy Consumption).
2.  **Classification Target (`y_clf`)**: A new binary column, `High_Renewable_Energy`, indicating whether the 'Value' is above the overall median, transformed to be 0 or 1.
"""

# Create the classification target variable 'High_Renewable_Energy'
# We use the median of the *scaled* 'Value' column to create the binary target for consistency with the scaled feature 'Value'.
median_scaled_value = merged_df['Value'].median()
merged_df['High_Renewable_Energy'] = (merged_df['Value'] > median_scaled_value).astype(int)

# Define features (X) and target variables (y)
X = merged_df.drop(columns=['Value', 'High_Renewable_Energy'])
y_reg = merged_df['Value']  # Target for regression
y_clf = merged_df['High_Renewable_Energy']  # Target for classification

print("Shape of X:", X.shape)
print("Shape of y_reg:", y_reg.shape)
print("Shape of y_clf:", y_clf.shape)
print("\nHigh_Renewable_Energy distribution:\n", y_clf.value_counts())

# Split the data for regression
X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(X, y_reg, test_size=0.2, random_state=42)

# Split the data for classification
X_train_clf, X_test_clf, y_train_clf, y_test_clf = train_test_split(X, y_clf, test_size=0.2, random_state=42, stratify=y_clf)

print("\n--- Data Split for Regression ---")
print(f"X_train_reg shape: {X_train_reg.shape}")
print(f"X_test_reg shape: {X_test_reg.shape}")
print(f"y_train_reg shape: {y_train_reg.shape}")
print(f"y_test_reg shape: {y_test_reg.shape}")

print("\n--- Data Split for Classification ---")
print(f"X_train_clf shape: {X_train_clf.shape}")
print(f"X_test_clf shape: {X_test_clf.shape}")
print(f"y_train_clf shape: {y_train_clf.shape}")
print(f"y_test_clf shape: {y_test_clf.shape}")

"""## 8. Applying Regression and Classification Algorithms

Now that our data is split, we can apply the chosen algorithms:

*   **Regression**: Linear Regression to predict `Value` (scaled renewable energy consumption).
*   **Classification**: Logistic Regression to predict `High_Renewable_Energy` (whether renewable energy consumption is above median).

### Linear Regression Model
"""

# Initialize and train the Linear Regression model
linear_reg_model = LinearRegression()
linear_reg_model.fit(X_train_reg, y_train_reg)

# Make predictions on the test set
y_pred_reg = linear_reg_model.predict(X_test_reg)

print("\n--- Linear Regression Model Trained ---")

"""### Logistic Regression Model"""

# Initialize and train the Logistic Regression model
logistic_reg_model = LogisticRegression(max_iter=1000, random_state=42)
logistic_reg_model.fit(X_train_clf, y_train_clf)

# Make predictions on the test set
y_pred_clf = logistic_reg_model.predict(X_test_clf)

print("\n--- Logistic Regression Model Trained ---")

"""## 9. Evaluating Model Performance

### Linear Regression Evaluation
"""

mse = mean_squared_error(y_test_reg, y_pred_reg)
r2 = r2_score(y_test_reg, y_pred_reg)

print(f"\nLinear Regression - Mean Squared Error: {mse:.4f}")
print(f"Linear Regression - R-squared: {r2:.4f}")

# Insight: Mean Squared Error indicates the average squared difference between actual and predicted values.
# R-squared represents the proportion of the variance in the dependent variable that is predictable from the independent variables.
# A higher R-squared (closer to 1) indicates a better fit. A lower MSE (closer to 0) indicates better prediction accuracy.

"""### Logistic Regression Evaluation"""

accuracy = accuracy_score(y_test_clf, y_pred_clf)
class_report = classification_report(y_test_clf, y_pred_clf)
conf_matrix = confusion_matrix(y_test_clf, y_pred_clf)

print(f"\nLogistic Regression - Accuracy: {accuracy:.4f}")
print("\nLogistic Regression - Classification Report:\n", class_report)
print("\nLogistic Regression - Confusion Matrix:\n", conf_matrix)

# Insight: Accuracy is the proportion of correctly classified instances.
# The Classification Report provides precision, recall, and F1-score for each class, giving a more detailed view of performance.
# The Confusion Matrix shows the counts of true positive, true negative, false positive, and false negative predictions.

"""## 10. Saving Models

As requested, I will save the trained Linear Regression and Logistic Regression models with today's date as part of their filenames.
"""

import joblib

today_date = datetime.date.today().strftime("%Y-%m-%d")

# Save Linear Regression model
linear_reg_filename = f"linear_regression_model_{today_date}.pkl"
joblib.dump(linear_reg_model, linear_reg_filename)
print(f"Linear Regression model saved as: {linear_reg_filename}")

# Save Logistic Regression model
logistic_reg_filename = f"logistic_regression_model_{today_date}.pkl"
joblib.dump(logistic_reg_model, logistic_reg_filename)
print(f"Logistic Regression model saved as: {logistic_reg_filename}")

"""## Final Insights and Model Error Explanations

### Linear Regression Insights:

*   **R-squared**: The R-squared value indicates how well the independent variables (Year, Temperature Change, and Country dummies) explain the variance in renewable energy consumption. A high R-squared (e.g., above 0.7-0.8) suggests that the model explains a large portion of the variability, while a low value indicates that many factors influencing renewable energy consumption are not captured by the model.
*   **Mean Squared Error (MSE)**: MSE is a measure of the average of the squares of the errors. A lower MSE indicates that the model's predictions are closer to the actual values. The context of the scaled 'Value' is important here; a small MSE on scaled data suggests good performance relative to the scaled range.
*   **Why the results are as they are**: If R-squared is high, it implies that factors like country-specific policies (captured by country dummies), general trends over time, and climate change indicators are good predictors of renewable energy consumption. If R-squared is low, it suggests that other socio-economic factors, technological advancements, or policy details not included in the dataset are also significant.

### Logistic Regression Insights:

*   **Accuracy**: The overall proportion of correctly predicted instances. While a good starting point, accuracy can be misleading in imbalanced datasets.
*   **Precision**: For the 'High Renewable Energy' class, precision tells us how many of the instances predicted as 'High' were actually 'High'. High precision means fewer false positives.
*   **Recall**: For the 'High Renewable Energy' class, recall tells us how many of the actual 'High' instances were correctly identified by the model. High recall means fewer false negatives.
*   **F1-Score**: The harmonic mean of precision and recall, providing a balanced measure, especially useful when class distribution is uneven.
*   **Confusion Matrix**: This matrix provides a breakdown of correct and incorrect predictions for each class. It helps identify if the model struggles more with one class (e.g., misclassifying 'Low' as 'High' or vice versa).
*   **Why the results are as they are**: The performance of the Logistic Regression model in classifying 'High_Renewable_Energy' depends on how clearly renewable energy consumption can be separated into two classes based on the features. If the features provide distinct patterns for high vs. low consumption, the model will perform well. If there's a lot of overlap or noise, the performance metrics will be lower. For example, if many countries fluctuate around the median, it becomes harder for the model to make a clear distinction, leading to more misclassifications.

## 7. Splitting Data into Training and Testing Sets

Before applying machine learning algorithms, we need to split our preprocessed data into features (X) and target variables (y), and then further divide them into training and testing sets. We will define two different target variables:

1.  **Regression Target (`y_reg`)**: `Value` (Renewable Energy Consumption).
2.  **Classification Target (`y_clf`)**: A new binary column, `High_Renewable_Energy`, indicating whether the 'Value' is above the overall median, transformed to be 0 or 1.
"""

# Create the classification target variable 'High_Renewable_Energy'
# We use the unscaled 'Value' median for a more intuitive threshold
# Let's get the median from the original renewable_energy_df to avoid issues with scaled values
original_value_median = pd.read_csv('/content/renewable_energy.csv')['Value'].median()

# Note: If we use the scaled 'Value' median, it will be close to 0
# For better interpretability, let's derive it from the unscaled data context
# However, since merged_df['Value'] is already scaled, we must be careful.
# Let's re-calculate it based on the scaled 'Value' for consistency with the scaled feature 'Value'.
# Median of a scaled variable is generally 0 if the original median is transformed.

# For the purpose of creating a classification target after scaling:
# If a value is above the median of the *scaled* 'Value' column, it's 'High_Renewable_Energy'
median_scaled_value = merged_df['Value'].median()
merged_df['High_Renewable_Energy'] = (merged_df['Value'] > median_scaled_value).astype(int)

# Define features (X) and target variables (y)
X = merged_df.drop(columns=['Value', 'High_Renewable_Energy'])
y_reg = merged_df['Value']  # Target for regression
y_clf = merged_df['High_Renewable_Energy']  # Target for classification

print("Shape of X:", X.shape)
print("Shape of y_reg:", y_reg.shape)
print("Shape of y_clf:", y_clf.shape)
print("\nHigh_Renewable_Energy distribution:\n", y_clf.value_counts())

# Split the data for regression
X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(X, y_reg, test_size=0.2, random_state=42)

# Split the data for classification
X_train_clf, X_test_clf, y_train_clf, y_test_clf = train_test_split(X, y_clf, test_size=0.2, random_state=42, stratify=y_clf)

print("\n--- Data Split for Regression ---")
print(f"X_train_reg shape: {X_train_reg.shape}")
print(f"X_test_reg shape: {X_test_reg.shape}")
print(f"y_train_reg shape: {y_train_reg.shape}")
print(f"y_test_reg shape: {y_test_reg.shape}")

print("\n--- Data Split for Classification ---")
print(f"X_train_clf shape: {X_train_clf.shape}")
print(f"X_test_clf shape: {X_test_clf.shape}")
print(f"y_train_clf shape: {y_train_clf.shape}")
print(f"y_test_clf shape: {y_test_clf.shape}")

"""## 8. Applying Regression and Classification Algorithms

Now that our data is split, we can apply the chosen algorithms:

*   **Regression**: Linear Regression to predict `Value` (scaled renewable energy consumption).
*   **Classification**: Logistic Regression to predict `High_Renewable_Energy` (whether renewable energy consumption is above median).

### Linear Regression Model
"""

# Initialize and train the Linear Regression model
linear_reg_model = LinearRegression()
linear_reg_model.fit(X_train_reg, y_train_reg)

# Make predictions on the test set
y_pred_reg = linear_reg_model.predict(X_test_reg)

print("\n--- Linear Regression Model Trained ---")

"""### Logistic Regression Model"""

# Initialize and train the Logistic Regression model
logistic_reg_model = LogisticRegression(max_iter=1000, random_state=42)
logistic_reg_model.fit(X_train_clf, y_train_clf)

# Make predictions on the test set
y_pred_clf = logistic_reg_model.predict(X_test_clf)

print("\n--- Logistic Regression Model Trained ---")

"""## 9. Evaluating Model Performance

### Linear Regression Evaluation
"""

mse = mean_squared_error(y_test_reg, y_pred_reg)
r2 = r2_score(y_test_reg, y_pred_reg)

print(f"\nLinear Regression - Mean Squared Error: {mse:.4f}")
print(f"Linear Regression - R-squared: {r2:.4f}")

# Insight: Mean Squared Error indicates the average squared difference between actual and predicted values.
# R-squared represents the proportion of the variance in the dependent variable that is predictable from the independent variables.
# A higher R-squared (closer to 1) indicates a better fit. A lower MSE (closer to 0) indicates better prediction accuracy.

"""### Logistic Regression Evaluation"""

accuracy = accuracy_score(y_test_clf, y_pred_clf)
class_report = classification_report(y_test_clf, y_pred_clf)
conf_matrix = confusion_matrix(y_test_clf, y_pred_clf)

print(f"\nLogistic Regression - Accuracy: {accuracy:.4f}")
print("\nLogistic Regression - Classification Report:\n", class_report)
print("\nLogistic Regression - Confusion Matrix:\n", conf_matrix)

# Insight: Accuracy is the proportion of correctly classified instances.
# The Classification Report provides precision, recall, and F1-score for each class, giving a more detailed view of performance.
# The Confusion Matrix shows the counts of true positive, true negative, false positive, and false negative predictions.

"""## 10. Saving Models

As requested, I will save the trained Linear Regression and Logistic Regression models with today's date as part of their filenames.
"""

import joblib

today_date = datetime.date.today().strftime("%Y-%m-%d")

# Save Linear Regression model
linear_reg_filename = f"linear_regression_model_{today_date}.pkl"
joblib.dump(linear_reg_model, linear_reg_filename)
print(f"Linear Regression model saved as: {linear_reg_filename}")

# Save Logistic Regression model
logistic_reg_filename = f"logistic_regression_model_{today_date}.pkl"
joblib.dump(logistic_reg_model, logistic_reg_filename)
print(f"Logistic Regression model saved as: {logistic_reg_filename}")

"""## Final Insights and Model Error Explanations

### Linear Regression Insights:

*   **R-squared**: The R-squared value indicates how well the independent variables (Year, Temperature Change, and Country dummies) explain the variance in renewable energy consumption. A high R-squared (e.g., above 0.7-0.8) suggests that the model explains a large portion of the variability, while a low value indicates that many factors influencing renewable energy consumption are not captured by the model.
*   **Mean Squared Error (MSE)**: MSE is a measure of the average of the squares of the errors. A lower MSE indicates that the model's predictions are closer to the actual values. The context of the scaled 'Value' is important here; a small MSE on scaled data suggests good performance relative to the scaled range.
*   **Why the results are as they are**: If R-squared is high, it implies that factors like country-specific policies (captured by country dummies), general trends over time, and climate change indicators are good predictors of renewable energy consumption. If R-squared is low, it suggests that other socio-economic factors, technological advancements, or policy details not included in the dataset are also significant.

### Logistic Regression Insights:

*   **Accuracy**: The overall proportion of correctly predicted instances. While a good starting point, accuracy can be misleading in imbalanced datasets.
*   **Precision**: For the 'High Renewable Energy' class, precision tells us how many of the instances predicted as 'High' were actually 'High'. High precision means fewer false positives.
*   **Recall**: For the 'High Renewable Energy' class, recall tells us how many of the actual 'High' instances were correctly identified by the model. High recall means fewer false negatives.
*   **F1-Score**: The harmonic mean of precision and recall, providing a balanced measure, especially useful when class distribution is uneven.
*   **Confusion Matrix**: This matrix provides a breakdown of correct and incorrect predictions for each class. It helps identify if the model struggles more with one class (e.g., misclassifying 'Low' as 'High' or vice versa).
*   **Why the results are as they are**: The performance of the Logistic Regression model in classifying 'High_Renewable_Energy' depends on how clearly renewable energy consumption can be separated into two classes based on the features. If the features provide distinct patterns for high vs. low consumption, the model will perform well. If there's a lot of overlap or noise, the performance metrics will be lower. For example, if many countries fluctuate around the median, it becomes harder for the model to make a clear distinction, leading to more misclassifications.
"""