# -*- coding: utf-8 -*-
"""Day7-(13-07-2026).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C0imVQcOjTtV-NyTRzgwWDzYnBm9D4d-
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.decomposition import PCA

# Upload Dataset
uploaded = files.upload()

# Read Dataset
df = pd.read_csv("used_phone_price_prediction_1M.csv")

print("========== FIRST 5 ROWS ==========")
print(df.head())

print("\n========== SHAPE ==========")
print(df.shape)

print("\n========== INFO ==========")
print(df.info())

print("\n========== DESCRIPTION ==========")
print(df.describe())

print("\n========== MISSING VALUES ==========")
print(df.isnull().sum())

# Fill Missing Values
for col in df.columns:
    if df[col].dtype == "object":
        df[col].fillna(df[col].mode()[0], inplace=True)
    else:
        df[col].fillna(df[col].mean(), inplace=True)

print("\nMissing Values After Cleaning")
print(df.isnull().sum())

# Convert Categorical Columns
label_encoder = LabelEncoder()

for col in df.select_dtypes(include='object').columns:
    df[col] = label_encoder.fit_transform(df[col].astype(str))

print("\nData after Encoding")
print(df.head())

# Feature Scaling
scaler = StandardScaler()
scaled_data = scaler.fit_transform(df)

print("\nFeature Scaling Completed")

# Elbow Method
wcss = []

for i in range(1,11):
    kmeans = KMeans(n_clusters=i, random_state=42, n_init=10)
    kmeans.fit(scaled_data)
    wcss.append(kmeans.inertia_)

plt.figure(figsize=(8,5))
plt.plot(range(1,11), wcss, marker='o')
plt.title("Elbow Method")
plt.xlabel("Number of Clusters")
plt.ylabel("WCSS")
plt.grid(True)
plt.show()

# KMeans Clustering
kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)

clusters = kmeans.fit_predict(scaled_data)

df["Cluster"] = clusters

print("\n========== CLUSTER COUNT ==========")
print(df["Cluster"].value_counts())

# Silhouette Score
score = silhouette_score(scaled_data, clusters)

print("\nSilhouette Score:", score)

# PCA Visualization
pca = PCA(n_components=2)

pca_result = pca.fit_transform(scaled_data)

plt.figure(figsize=(8,6))
plt.scatter(
    pca_result[:,0],
    pca_result[:,1],
    c=clusters,
    cmap="viridis"
)

plt.title("K-Means Clustering")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.colorbar(label="Cluster")
plt.show()

# Cluster Summary
print("\n========== CLUSTER SUMMARY ==========")
print(df.groupby("Cluster").mean())

# Correlation Heatmap
plt.figure(figsize=(12,8))
sns.heatmap(df.corr(), cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

# Save Output
df.to_csv("Day7_KMeans_Output.csv", index=False)

print("\nOutput file saved as Day7_KMeans_Output.csv")

files.download("Day7_KMeans_Output.csv")

print("\n========== INSIGHTS ==========")
print("1. Dataset loaded successfully.")
print("2. Missing values handled.")
print("3. Categorical columns encoded.")
print("4. Data standardized using StandardScaler.")
print("5. Elbow Method used to choose clusters.")
print("6. K-Means clustering performed.")
print("7. Silhouette Score calculated.")
print("8. PCA used for cluster visualization.")
print("9. Cluster summary generated.")
print("10. Final dataset saved successfully.")